name: susanin
description: Susanin.

publish_to: 'none'

version: 3.0.1+36

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.18.0
  intl: ^0.19.0
  geolocator: ^13.0.1
  wakelock_plus: ^1.2.8
  flutter_compass: ^0.8.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  shimmer: ^3.0.0
  lottie: ^3.1.2
  maps_launcher: ^2.2.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  # flutter_lints: ^3.0.1
  lint: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/icon_ios.png"
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  adaptive_icon_background: "assets/icon/icon_bg.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/icon/

flutter_intl:
  main_locale: en
  enabled: true