name: susanin
description: Susanin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.5+28

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  intl: ^0.17.0
  geolocator: ^8.2.0
  wakelock: ^0.6.1+2
  flutter_compass: #laggy on android with version 0.7.0 from pub.dev, so get it from github
    git:
      url: https://github.com/hemanthrajv/flutter_compass.git
      ref: master
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  share_plus: ^4.0.4
  shimmer: ^2.0.0
  lottie: ^1.3.0
  maps_launcher: ^2.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^1.1.8
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/icon_ios.png"
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  adaptive_icon_background: "assets/icon/icon_bg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/animations/
    - assets/icon/