name: susanin
description: Susanin.

publish_to: 'none'

version: 3.0.1+36

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7
  collection: ^1.18.0
  intl: ^0.19.0
  geolocator: ^13.0.2
  wakelock_plus: ^1.2.10
  flutter_compass: ^0.8.1
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  lottie: ^3.3.1
  maps_launcher: ^3.0.0+1
  rxdart: ^0.28.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  # flutter_lints: ^3.0.1
  lint: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/icon_ios.png"
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  adaptive_icon_background: "assets/icon/icon_bg.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/icon/

flutter_intl:
  main_locale: en
  enabled: true