import 'package:flutter/material.dart';
import 'package:susanin/features/places/domain/entities/icon_entity.dart';

class IconConstants {
  const IconConstants._();

  static final standard = IconEntity(
    iconData: Icons.location_on,
    color: colors.first,
  );

  static const colors = [
    Colors.white,
    Colors.black,
    Colors.red,
    Colors.blue,
    Colors.yellow,
    Colors.purple,
    Colors.teal,
  ];

  static const icons = [
    Icons.location_on_rounded,
    Icons.explore_rounded,
    Icons.self_improvement_rounded,
    Icons.accessibility_new_rounded,
    Icons.directions_bike_rounded,
    Icons.downhill_skiing_rounded,
    Icons.hiking_rounded,
    Icons.delivery_dining_rounded,
    Icons.agriculture_rounded,
    Icons.airport_shuttle_rounded,
    Icons.directions_bus_rounded,
    Icons.directions_car_filled_rounded,
    Icons.directions_boat_filled_rounded,
    Icons.airplanemode_active_rounded,
    Icons.access_time_filled_rounded,
    Icons.account_balance_rounded,
    Icons.account_balance_wallet_rounded,
    Icons.account_circle_rounded,
    Icons.adjust_rounded,
    Icons.alternate_email_rounded,
    Icons.anchor_rounded,
    Icons.apartment_rounded,
    Icons.apple_rounded,
    Icons.archive_rounded,
    Icons.navigation_rounded,
    Icons.assistant_photo_rounded,
    Icons.attach_money_rounded,
    Icons.attractions_rounded,
    Icons.audiotrack_rounded,
    Icons.auto_awesome_rounded,
    Icons.back_hand_rounded,
    Icons.backpack_rounded,
    Icons.bakery_dining_outlined,
    Icons.battery_5_bar_rounded,
    Icons.beach_access_rounded,
    Icons.bed,
    Icons.bug_report_rounded,
    Icons.build_rounded,
    Icons.business_center_rounded,
    Icons.cabin_rounded,
    Icons.cake_rounded,
    Icons.call_rounded,
    Icons.camera_alt_rounded,
    Icons.casino_rounded,
    Icons.castle_rounded,
    Icons.catching_pokemon_outlined,
    Icons.category_rounded,
    Icons.celebration_rounded,
    Icons.chair_rounded,
    Icons.charging_station_rounded,
    Icons.child_friendly_rounded,
    Icons.cloud_rounded,
    Icons.cookie_rounded,
    Icons.credit_card_rounded,
    Icons.cruelty_free_rounded,
    Icons.dark_mode_rounded,
    Icons.deck_rounded,
    Icons.desktop_windows_rounded,
    Icons.diamond_rounded,
    Icons.dining_rounded,
    Icons.eco_rounded,
    Icons.egg_rounded,
    Icons.emoji_emotions_rounded,
    Icons.emoji_nature_rounded,
    Icons.emoji_objects_rounded,
    Icons.favorite_rounded,
    Icons.forest_rounded,
    Icons.grade_rounded,
    Icons.grass_rounded,
    Icons.health_and_safety_rounded,
    Icons.local_fire_department_rounded,
    Icons.palette_rounded,
    Icons.pets_rounded,
    Icons.phishing_rounded,
    Icons.shopping_basket_rounded,
    Icons.sports_bar_rounded,
    Icons.ac_unit_rounded,
  ];
}
